# fly.toml app configuration file generated for worldspritesserver on 2023-06-05T11:33:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "worldspritesserver"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200